### ISSUE TITLE
Home page header

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#11]
Could we make it so that when you scroll or when Menu button is clicked, the header turns into the same one that we have in all the other pages (the small version)? Like so:

![menu bar mockup](https://cloud.githubusercontent.com/assets/13275142/20641771/278c2386-b3f7-11e6-9c70-3f3e05bc5d88.jpg)

When scrolling it could be similar behaviour like here: http://99u.com/

**Comment by limzykenneth** [comment]
yea, should be possible

**Comment by limzykenneth** [comment]
Deployed
