### ISSUE TITLE
Top bar inconsistency

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#17]
Inconsistency: ie Event post appears differently (different amount of space) when opened from home page and from events page. (See screengrabs) Also, purple bar should appear everywhere except home page.

<img width="1279" alt="screen shot 2016-12-06 at 07 30 13" src="https://cloud.githubusercontent.com/assets/13275142/20960073/7914a856-bc56-11e6-8e52-4605b58f16f7.png">
<img width="1280" alt="screen shot 2016-12-06 at 07 29 53" src="https://cloud.githubusercontent.com/assets/13275142/20960072/7914b936-bc56-11e6-89c6-73f324672f92.png">

**Comment by limzykenneth** [comment]
This should already been solved, try refreshing your browser and try again. Let me know if it still doesn't work.

**Comment by jiurate** [comment]
Currently this post appears blank when opened

**Comment by limzykenneth** [comment]
@jiurate Fixed

**Comment by jiurate** [comment]
👍 👍 👍
