### ISSUE TITLE
Jobs&Opps posts on Home/Media page

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#19]
Sub-categories on Jobs&Opps posts should appear like, ‘Jobs&Opps: Full-Time’, ‘Jobs&Opps: Freelance’ etc, similarly like with Events posts. (I think it’s ok to abbreviate?)

**Comment by limzykenneth** [comment]
Maybe, might want to confirm with @lukefutures about this though.

**Comment by limzykenneth** [comment]
Deployed
