### ISSUE TITLE
Image slider on home page

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#2]
Could there be an option to add text in the image slider, instead of the images too? So that the description about UAL Futures could go in there too? The text could be centered and the same size as page-name element.

**Comment by limzykenneth** [comment]
Yup, on the backend under the "Slideshow" post type you can have a look at the form in there. You can choose to upload an image or type in some text. Apparently Luke only uploaded images so there's only images now.
