### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#22]
Implement search page. Also add button in the menu bar (will supply it later on)

**Comment by limzykenneth** [comment]
Ready for the button in the menu bar

**Comment by jiurate** [comment]
[Search Button.svg.zip](https://github.com/limzykenneth/ualfutures-frontend/files/660436/Search.Button.svg.zip)

**Comment by limzykenneth** [comment]
@jiurate I just had a closer look at the search page, is it searching tags only?

**Comment by limzykenneth** [comment]
Deployed but it's a bit weird in terms of UX i think. Have a try

**Comment by jiurate** [comment]
Why do you think it is weird, Kenneth?

**Comment by limzykenneth** [comment]
@jiurate Hmm...been awhile, can't really remember why now. Might not be that big of a problem anyway.

**Comment by jiurate** [comment]
Noticed that search is case sensitive, when typing (only shows results if the case matches, ie if I type css, the tag CSS doesn't appear). Although after clicking enter, the relevant results are shown as posts, even if the case was different. Is it possible to make live search results case-insensitive?

**Comment by limzykenneth** [comment]
yeah, forgot about that. Thanks

**Comment by limzykenneth** [comment]
Done
