### ISSUE TITLE
Registration page on 13"

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#23]
<img width="1280" alt="screen shot 2016-12-07 at 08 33 37" src="https://cloud.githubusercontent.com/assets/13275142/20960393/28f0616a-bc58-11e6-89b4-3cb0c871f259.png">

**Comment by limzykenneth** [comment]
Deployed. Should work fine on 13" and maybe all tablets, smaller than that (phones etc) will need to be dealt with when we work on responsiveness.
