### ISSUE TITLE
UAL logo on home page

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#3]
Could you change the colour to that bright blue, to match the other elements at the top?

**Comment by limzykenneth** [comment]
@jiurate do you have an illustrator or SVG version of it?

**Comment by jiurate** [comment]
[UAL logo.svg.zip](https://github.com/limzykenneth/ualfutures-frontend/files/614278/UAL.logo.svg.zip)

**Comment by limzykenneth** [comment]
Deployed
