### ISSUE TITLE
Image width in a post

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#33]
In a post, could you please make all images always have the same width (same as text width)?

**Comment by limzykenneth** [comment]
that is controlled by the WYSIWYG editor, I can make it so that it affects all images but there won't be a way to opt out after that.

**Comment by jiurate** [comment]
I think it's better, no? Currently the width varies, like in the attached screenshots, and it just looks arbitrary, like it hasn't been designed properly. What does it depend on? Is it because the image size is not enough width to cover the column? If that's the case let's double check with Luke, would it be better if whoever uploads the images always uploads them big enough?

PS When you say it would affect all images, you mean all images uploaded in the post (not for the featured image on home/media page for example)?

<img width="1280" alt="screen shot 2017-01-31 at 07 34 27" src="https://cloud.githubusercontent.com/assets/13275142/22456066/1583d43a-e788-11e6-887d-83c325f716ba.png">

<img width="1279" alt="screen shot 2017-01-31 at 07 34 41" src="https://cloud.githubusercontent.com/assets/13275142/22456069/1921bdbe-e788-11e6-8a3a-6ad656ae6b8b.png">

**Comment by limzykenneth** [comment]
It is basically whatever size you set it to be in the editor. I can style it so that all the images in the content part ie. those added in the editor to be of the same width

**Comment by jiurate** [comment]
I'm not sure I understand.

**Comment by limzykenneth** [comment]
Let me have a closer look, I'll let you know later today

**Comment by limzykenneth** [comment]
@jiurate Have a look now

**Comment by jiurate** [comment]
I think that's great
