### ISSUE TITLE
Home page slider text (mobile)

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#35]
The text is at the top of the slider box (see attached screenshot), should be in the middle of the box 

<img width="696" alt="screen shot 2017-01-30 at 06 18 10" src="https://cloud.githubusercontent.com/assets/13275142/22416120/398a2952-e6c4-11e6-8436-7375e9668d30.png">

**Comment by limzykenneth** [comment]
Done
