### ISSUE TITLE
Directory page: source

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#38]
Is the source line implemented in the directory posts (as in original artwork – see image)?

<img width="889" alt="screen shot 2017-01-30 at 08 18 31" src="https://cloud.githubusercontent.com/assets/13275142/22416195/d523a3de-e6c4-11e6-928c-d674b2a5363b.png">

**Comment by limzykenneth** [comment]
It's in there, just that at the moment the "Written By" field was not filled in by any post

**Comment by jiurate** [comment]
Okay great thank you!
