### ISSUE TITLE
Mobile/Tablet: menu

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#40]
Please could you update the menu with a conventional burger (see below), as you’ve suggested earlier?
Also, when clicked, could you make the menu appear from the top (rather than from the left?) or not animate at all

![320x568 - burger](https://cloud.githubusercontent.com/assets/13275142/22416380/22a58590-e6c6-11e6-9921-8810dd7cf179.jpg)

**Comment by jiurate** [comment]
One more thing, after the new addition of two items, the menu on mobile doesn't fit:

![img_9530](https://cloud.githubusercontent.com/assets/13275142/22538052/8c0316a4-e907-11e6-8c04-81e3efb177f1.jpg)

Could you reduce the text size; and format it slightly differently (sorry I should have designed it this way the first time: main menus in medium font, and submenus in regular, also with half line break between the menu and submenu, and full line break between the different main menu sections). Could we also include search on mobile? Please see below.

![mobile menu - 3](https://cloud.githubusercontent.com/assets/13275142/22538127/084a0768-e908-11e6-8c1f-db64604031cd.jpg)

Could you also align the ual and burger with the edges of the rectangles that are below (so that they have the same margins on the sides)?

<img width="879" alt="screen shot 2017-02-02 at 00 26 24" src="https://cloud.githubusercontent.com/assets/13275142/22538369/d47bc8ca-e909-11e6-8735-6c9dbafa6514.png">

**Comment by limzykenneth** [comment]
@jiurate on the last point, I might be staring at it for too long, can you let me know which one needs to move to even up the margin?

**Comment by jiurate** [comment]
Sorry that wasn't clear. I meant to move ual logo and burger inwards a bit so that it lines up with the margin of the rectangles:

![mobile-menu](https://cloud.githubusercontent.com/assets/13275142/22539366/8238157a-e911-11e6-9c26-2f28668a8f9d.jpg)

Actually the same with the desktop version: could Futures logo and search button align with the margin?

<img width="1042" alt="screen shot 2017-02-02 at 06 34 37" src="https://cloud.githubusercontent.com/assets/13275142/22539403/c8217b9e-e911-11e6-8801-748fc56088ca.png">

Sorry these are very small cosmetic changes but they make a difference.

**Comment by limzykenneth** [comment]
ok. I'm not seeing the last one with the full size though

**Comment by jiurate** [comment]
![desktop-menu](https://cloud.githubusercontent.com/assets/13275142/22539878/da3de88c-e914-11e6-8f2c-5286d80a87a5.jpg)

So here it would be ideal if Futures logo was moved to the right so it lines up with that pink line, and the whole menu bar moved to the right too up to the pink line.

**Comment by limzykenneth** [comment]
Have a look if it's better now. I'm not seeing the Futures logo in that position though. What is your screen size?

**Comment by jiurate** [comment]
Yes, perfect, the only time Futures logo is still outside the margin is when the bar is big (when it shrinks it's fine) and a tiny bit of the newsletter:

![f-large-menu](https://cloud.githubusercontent.com/assets/13275142/22540222/d46f6dac-e916-11e6-9a80-890f6f383edc.jpg)

![newsletter](https://cloud.githubusercontent.com/assets/13275142/22540224/d854c6b0-e916-11e6-92d3-2ba0d6142fcd.jpg)

I've checked it on 13" retina, and a bigger screen, 1920x1200 non-retina.

**Comment by limzykenneth** [comment]
ok done

**Comment by jiurate** [comment]
❤️

**Comment by jiurate** [comment]
Sorry to reopen this again, but on mobile (I'm on iPhone 4s, so rather small), the menu still doesn't fit, could you please make the font smaller or make it scrollable?

![img_9590](https://cloud.githubusercontent.com/assets/13275142/22760802/0261d39c-ee50-11e6-84c5-30b7df27b88a.jpg)

![img_9589](https://cloud.githubusercontent.com/assets/13275142/22760811/06b0516c-ee50-11e6-8ffb-62fe667b206a.jpg)



Also, the spaces are still the same between menu groups and elements, could you please adjust the leading so that it is clear that Events–Features belong to Media, and Register–Method belong to Studio? See below (different colour squares signify different distances between elements):

![084a0768-e908-11e6-8c1f-db64604031cd copy](https://cloud.githubusercontent.com/assets/13275142/22760742/ad7db3e6-ee4f-11e6-8d31-a1dfe681a5d9.jpg)
