### ISSUE TITLE
Website crashing on iPhone

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#43]
Not sure if it is my phone that’s out of date (iPhone 4s) but the website keeps crashing (screenshot attached)

**Comment by limzykenneth** [comment]
@jiurate You didn't attached the screenshot?

**Comment by jiurate** [comment]
I'm sorry! Here it is.

![img_9503](https://cloud.githubusercontent.com/assets/13275142/22456236/2c2ed1c0-e789-11e6-99fd-3616c779308b.jpg)

**Comment by limzykenneth** [comment]
hmm....I can't really tell why that is happening...

**Comment by jiurate** [comment]
seems to have been working fine recently!
