### ISSUE TITLE
Consistent use of tags

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#46]
Could the tags be edited so they all follow the same format, ie: 
• use upper and lowercase
• use spaces between words 
• do not use #
• abbreviations are capitalised

All the existing tags should be in this format (or removed as indicated):
CSS
Tools
Web Design
Interview
Full-Time (should be removed, as it has a label of the same title)
Internship (should be removed, as it has a label of the same title)
Alumni
CSM
Data
AI
Collaboration (currently there are two tags, ‘Collaboration’ and ‘collaboration)
Futures Studio
Futures Talks
IAM
LCC
UAL

**Comment by limzykenneth** [comment]
Tags need to be edited in Wordpress under individual posts, the front end just fetch all available ones from there
