### ISSUE TITLE
Loading page

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#47]
Could loading page simply be the background. As it loads up pretty quickly, it's just that all these elements that aren't supposed to be on home page, shows up while loading.
What do you think?

**Comment by limzykenneth** [comment]
it needs some kind of indication something is loading, as for most people a couple seconds loading time can be confusing (not sure if the website crashed or it is loading). For home page I'll see if I can just make it the home top bar while loading, at least there's something on screen.

**Comment by jiurate** [comment]
Okay, I'll send a little gif. Any recommendations for size limit?

**Comment by limzykenneth** [comment]
As small as possible, ideally less than 50kb

**Comment by limzykenneth** [comment]
@jiurate Have a look now, if you think the UX is ok then we don't need the loading gif

**Comment by jiurate** [comment]
I think it's probably enough, but I made a lil gif just in case anyway. 

![loading-1](https://cloud.githubusercontent.com/assets/13275142/22537326/a185f362-e901-11e6-9167-1e73bb0d2703.gif)


Could be a similar size as here maybe?
![loading-size](https://cloud.githubusercontent.com/assets/13275142/22537330/a6bb1a60-e901-11e6-9a90-5ad13ec6c4bb.jpg)

Though actually not sure if it's better just on its own on white background or among the other elements, as in screenshot.

**Comment by limzykenneth** [comment]
If you think without a loading gif work then maybe don't add it in. If you want to add it in it might be better to have it with the headers just to indicate what is loading.

**Comment by jiurate** [comment]
Let's keep as it is
