### ISSUE TITLE
Subscribe to Newsletter fields

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#49]
Can ‘What do you do? *’ field be styled differently? At the moment it’s not white, it’s grey or have a gradient (on mobile), wonder if it could be white as other fields?

**Comment by limzykenneth** [comment]
it's the same situation as on http://ualfutures.studio. Restyling it is not easy, needs to rebuild the whole element from scratch.

**Comment by jiurate** [comment]
Okay, no problem. Thought I'd double check.

**Comment by jiurate** [comment]
One more thing, can't remember if I've asked this one before either: 
'What do you do?*' text cannot be centered in the field either, like the other ones, right?

**Comment by limzykenneth** [comment]
yeah

**Comment by jiurate** [comment]
No problem
