### ISSUE TITLE
Tablet size

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#50]
Is it still possible to implement tablet size? 
As when browser resized in between desktop and mobile size, the rectangles don't line up nicely, and text is messy (see attached).

I've also attached an artwork for 700px width.

<img width="842" alt="screen shot 2017-01-30 at 08 08 19" src="https://cloud.githubusercontent.com/assets/13275142/22416738/4e8f55a8-e6c8-11e6-906e-842cedc1453a.png">

<img width="843" alt="screen shot 2017-01-30 at 08 08 29" src="https://cloud.githubusercontent.com/assets/13275142/22416743/530f24be-e6c8-11e6-8d79-e4af950d7660.png">

[700x950 Folder.zip](https://github.com/limzykenneth/ualfutures-frontend/files/738400/700x950.Folder.zip)

**Comment by limzykenneth** [comment]
Tweaked it a little, should transition smoothly across all screen sizes now

**Comment by jiurate** [comment]
It's better! But still some in between cramming... I assume that it's a lot of work to make it into two columns, right? Would you be able to tweak it just a little bit more so that this doesn't happen? — 

<img width="921" alt="screen shot 2017-02-01 at 20 55 33" src="https://cloud.githubusercontent.com/assets/13275142/22537600/d7ad5118-e903-11e6-9221-8c8a0444cda7.png">
