### ISSUE TITLE
Post feature level / size

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#51]
I've been doing a bit of testing on the wordpress and I have a question about the different sizes of feature posts, as I can't remember what exactly we agreed. What do these 0-1-2 stand for? 

<img width="210" alt="screen shot 2017-02-02 at 00 47 46" src="https://cloud.githubusercontent.com/assets/13275142/22538573/46907478-e90b-11e6-882a-541498d716c4.png">

Currently all three seem to format the post in the same way on home/media page. I was thinking that it would have the following 3 options:

• no image, medium-sized (as the Futures event), colour: dark-blue (instead of the current bright green). 
• with image, medium-sized
• with image, large-sized – like currently

Below is how this shows up when the post is uploaded at any level, when no image is chosen:

<img width="647" alt="screen shot 2017-02-02 at 00 32 59" src="https://cloud.githubusercontent.com/assets/13275142/22538643/dc8fc064-e90b-11e6-91ac-d88e8565819c.png">

**Comment by limzykenneth** [comment]
I don't think that is actually being used already as we previously already established that all features will be big, futures events will be medium and everything else small (something like that), so they are hard coded in now and not using the value of this field

**Comment by jiurate** [comment]
So the 'Post feature level' field is currently redundant?


Could you please make the colours of the feature post (when no featured image is chosen) like this (forgot to mention in the above comment):

![screen shot 2017-02-08 at 22 07 31](https://cloud.githubusercontent.com/assets/13275142/22759932/2acbb180-ee4c-11e6-9379-28d3d7fbb2e1.png)

**Comment by limzykenneth** [comment]
Yeah, I probably should remove that field for now.

All Feature posts? OK.

**Comment by limzykenneth** [comment]
Fontend bit done. I'll change all backend stuff a bit later together.

**Comment by limzykenneth** [comment]
Done in backend as well
