### ISSUE TITLE
Directory format

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#52]
Sorry, this is something I overlooked previously. 

<img width="975" alt="screen shot 2017-02-02 at 00 10 41" src="https://cloud.githubusercontent.com/assets/13275142/22538825/525bdb6a-e90d-11e6-9ee6-b244066ed392.png">

Did we decide to keep 3 columns for directory (instead of making it into 4)?
In which case it doesn't really make sense to format these in a different way than everything else. Originally it was formatted differently in the artwork so that the text and image could fit into the small boxes and still remain readable/functional (and 4 column grid was in order to fit more links on the screen – as it is essentially a visual list).

I imagine that would involve quite a bit of more work and fiddling around. 
Should we revert them to the same format as the rest?

**Comment by limzykenneth** [comment]
There should be a 4 column grid, I'm not sure how the bug occur but it does happens sometimes. I suspect it happens more because of resizing windows but I'm not sure

**Comment by jiurate** [comment]
You're right, there are 4 columns on a big screen, that's fine.

A few things to fix then:

1. Images inside the box should always be the same width and height. Is it possible? Currently the gif is smaller in both width and height, and the other two images vary in height too:
![screen shot 2017-02-08 at 21 50 33](https://cloud.githubusercontent.com/assets/13275142/22759035/e1ed2500-ee48-11e6-96da-e84a4fc47f81.png)

And on mobile currently the width of images vary too.

2. The gap between the top edge of the box and the cap-height of text should be the same as the gap between top edge of the box and the image:

![screen shot 2017-02-08 at 20 52 15 copy](https://cloud.githubusercontent.com/assets/13275142/22757088/6111b16e-ee41-11e6-8c94-7dc0c5ccb106.png)

3. At certain smaller screens (basically between the size when it turns into a 3-column grid, and up to the point when it turns into one column), this happens:

![screen shot 2017-02-08 at 21 17 42](https://cloud.githubusercontent.com/assets/13275142/22758448/abfa86ec-ee46-11e6-84d3-b0f662a518b6.png)

I've entered sources, so that there's text element at the bottom of the box, as guidance. 
The gap between the bottom of image and the cap-height of title should never be smaller than the gap between the bottom baseline of title and the source. Attached below is how the minimum distance should look like. Perhaps the height of the box should be bigger on 3-column grid, so that the ratio of the box is closer to the one on 4-column grid? 

![screen shot 2017-02-08 at 21 20 17 copy](https://cloud.githubusercontent.com/assets/13275142/22758120/3d6139b6-ee45-11e6-88ab-574511a11bed.png)

4. Small detail on Wordpress. Is it possible, in Directory, change the word 'Authors' to 'Source Name'? Might be easier to understand for whoever is uploading content:

![screen shot 2017-02-08 at 21 07 04](https://cloud.githubusercontent.com/assets/13275142/22758455/b5464a38-ee46-11e6-8527-880e05891c9f.png)

**Comment by limzykenneth** [comment]
1. They should be of the same width, might be some bugs I'll have a look. For same height, do you mean cropping the image so that they have the same height as well?
1. That is fine.
1. I'll try and tweak that more.
1. I'm not sure this can be changed easily as that field might be shared across all the post types, I'll have a look.

**Comment by limzykenneth** [comment]
1, 2, 3 done

**Comment by limzykenneth** [comment]
4 done. I've just added a bit more description tot he field title and placeholder, should explain it I think.
