### ISSUE TITLE
Home page top bar

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#53]
Talking about lining up, one more little improvement: could you line ual logo and menu up like this (and add search button), as these are otherwise the only elements that ever jump outside the margins:

![home-page-menu](https://cloud.githubusercontent.com/assets/13275142/22539986/748ee0a8-e915-11e6-95a9-700737e8a143.jpg)

**Comment by limzykenneth** [comment]
for the ual logo when you bring up the regular nav bar it would seem to move out of the margin though (at the moment it would seemed to stay in the same place just colours changed)

**Comment by jiurate** [comment]
Yes, I see what you mean. However, I think as a front page it would look much better (I was wrong to design those elements floating like that, I think) and when on the blue bar it would look as if Futures logo just pushed ual – and it still looks good because it is contained within the bar and because of al the margins around it corresponding nicely). I don't think it's essential that UAL logo stays in the same spot.

I've attached the example (when switching from one image to the other, I think it looks good).
Is it a pain to re-fiddle ual logo and menu position on home screen (plus add search button)?

![01-futures-home](https://cloud.githubusercontent.com/assets/13275142/22762807/1b20ddac-ee59-11e6-8631-0ad57a91ef8e.jpg)

![02-futures-home](https://cloud.githubusercontent.com/assets/13275142/22762813/1fa520fe-ee59-11e6-8fe1-6185deec54e6.jpg)

**Comment by limzykenneth** [comment]
Ok sure, shouldn't be too hard

**Comment by limzykenneth** [comment]
done
