### ISSUE TITLE
Sizing of boxes

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#6]
For directory and jobs&opps posts: there shouldn't be an option to choose the size, they should always be small.
Event posts: they should always appear as small, too, unless it's a Futures event – then it should be medium. Is it possible to do it so that there isn't an option to choose this, but the system select it depending which type of even it is?

**Comment by limzykenneth** [comment]
Yeah, should be able to. Not for the events yet though, that will need the categories stuff to be sorted out first obviously.

**Comment by limzykenneth** [comment]
Deployed
