### ISSUE TITLE
Image slider arrows

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#7]
Could you replace the arrows with these ones?

[Arrows.zip](https://github.com/limzykenneth/ualfutures-frontend/files/614297/Arrows.zip)

**Comment by jiurate** [comment]
[Arrows.zip](https://github.com/limzykenneth/ualfutures-frontend/files/614296/Arrows.zip)

**Comment by limzykenneth** [comment]
Hey @jiurate, can you send me the SVG version of these arrows, scaled down currently they appear quite thin, might need to either use a vector version or create a new version with the right size.

**Comment by jiurate** [comment]
Sorry to change this, but could we do the arrows in a different style, like in this screenshot? So that it doesn't interfere with the image on a small screen.

![screen shot 2016-12-19 at 08 14 48](https://cloud.githubusercontent.com/assets/13275142/21305447/b99bf1e2-c5c3-11e6-9417-3a24fb463eb2.png)

[Arrows.zip](https://github.com/limzykenneth/ualfutures-frontend/files/660483/Arrows.zip)

**Comment by limzykenneth** [comment]
Deployed
