### ISSUE TITLE
UAL logo link

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#8]
We thought that it's confusing to link UAL logo to UAL website, because intuitively we would click on the top left to go back to home page. Need to consult with Luke about that, but for the sake of linking to UAL I think there would be other opportunities to do so?

**Comment by limzykenneth** [comment]
All depends on UAL's style guide probably.

**Comment by jiurate** [comment]
Luke confirmed that the link can be removed from UAL logo (linking to UAL website).
Do you think it should still have a link leading back to hompege, or only Futures logo should have that?

**Comment by limzykenneth** [comment]
I think it is expected to link to homepage, but I'm not sure if it is weird or not

**Comment by limzykenneth** [comment]
Linked to homepage

**Comment by jiurate** [comment]
👌👍
