### ISSUE TITLE
Subcategories selector

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#9]
After the subcategories are implemented in the back-end, could you add them in front-end too, like here:

http://felixsteindl.com/ual-test/events.html
http://felixsteindl.com/ual-test/jobs.html

And same for directory as in the mockup:

[04 Directory.pdf](https://github.com/limzykenneth/ualfutures-frontend/files/614310/04.Directory.pdf)

**Comment by limzykenneth** [comment]
- [x] Implement on backend
- [x] Add special case for Events grid card
- [x] Directory page
- [x] Colour coding

**Comment by limzykenneth** [comment]
@felixsteindl @jiurate Please review and let me know if there's anything missing in terms of subcategories. If not just close this issue then.

**Comment by jiurate** [comment]
Can we add Past Futures Events category? All Futures events with a date that’s passed should be filtered in there.

Although we might need a different wording, need to consult with Luke.

Also, the one that is currently selected could be underlined. And we need a way to go back to show all. Perhaps we need another button that says 'All.
